name: life_simulation_game
description: A life simulation game built with Flutter using clean architecture principles.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Navigation
  go_router: ^14.2.7
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  
  # UI
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  
  # Utilities
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.4.2
  intl: ^0.19.0
  
  # Architecture
  injectable: ^2.4.4
  get_it: ^7.7.0
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  injectable_generator: ^2.6.2
  
  # Testing
  mockito: ^5.4.4
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^4.0.0
  
  # Additional testing tools
  test: ^1.25.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700